language: node_js
node_js:
  - "8"
  - "10"
jobs:
  include:
    - name: "windows"
      os: windows
      install:
      before_script:
        - npm install lerna
        - npm run bootstrap
    - name: "linux"
      os: linux
      install:
      before_script:
        - npm install lerna
        - npm run bootstrap