language: node_js
node_js:
  - "8"
  - "10"
before_script:
  - npm --version
  - find . -iname package-lock.json -delete
  - find . -iname node_modules -type d -exec rm -rv {} \;
  - npm cache clean --force
  - npm install
  - npm run install-all
