language: rust
dist: trusty

rust:
  - stable

before_install:
  - source $HOME/.nvm/nvm.sh
  - nvm install 8
  - nvm use 8
  - node -v
  - npm -v

jobs:
  include:
    - name: "windows"
      os: windows
      before_script:
        - npm run bootstrap
    - name: "linux"
      os: linux
      before_script:
        - npm run bootstrap
    - name: "osx"
      os: osx
      before_script:
        - npm run bootstrap
