dist: trusty
language: node_js
node_js:
- 8
deploy:
  provider: releases
  api_key:
    secure: xZGYRJ5E4BnUgRBDIkqeNqDSyUdvZAOJHqey73ZpHfs834kKhJ3x5MMmHdvP0bXA+OVUu+fnIfuuNH158hc7Mo0BPkJN4nkOcl0wjNUpqfg2ujAfcbAehtkz1cpv8AZRNSrL1xrtchOEY7jnuGyv+O05uROxTxvtT3TsGql1Qc62M+MglZtz2bALMbFrTMfxqcXH32h431OIXKZORkQUXgsFvbXg0J2ghzDLMknTlDZF2W2/Xds77FTPe9B7gNiNRvL9y5bU/Y03k1efIcfdMNSL8upGhpPhgDiipPjGFUmyarfcXvd6v2HQNrPTAHXoXHReIqAapNUqU5bWMQ9Kd+f5BAfybKIce6q+m4JvcoritCUJBP9uV9+7oA8rek0Cvykfc1MGFWHSy5Wv1iheUh9T3i/hlrqSZqad0LYw7tHQg1JLbFQOaqlIBmy8fYFsV3k9L1222u9EdWzHTO5kpHOHXeXRaeKrHCMycVWcVINXfKXrMIWO4sxAY71IRBTLQJUFPUUTjcSgkWB0yHZFyli8qEJmVvZikcylz89eVY2iTJepddKnsnSWPOQP1ZA1JRLP0QjhcWMfHPrrMWm2WUfBNebIkmPQylidWkvPBHca4HM7DTYuV9BbOZiR8prQ58v7zEVTxxr9ODFeFcjRcYaFpa+nQKRzSUdvsO1zUpU=
  file_glob: true
  file:
  - build/appimage-build*/n3h*
  - build/electron-build/dist/n3h*
  skip_cleanup: true
  draft: true
  prerelease: true
  name: $TRAVIS_TAG
  on:
    tags: true
    repo: holochain/n3h

jobs:
  include:
  - name: windows test
    os: windows
    script:
    - npm test
  - name: linux test
    os: linux
    script:
    - npm test
  - name: osx test
    os: osx
    script:
    - npm test
  - name: linux-x64 build
    if: tag IS present
    os: linux
    services: docker
    script:
    - VM_ARCH=x64 ./build/release-build-appimage.bash
  - name: linux-aarch64 build
    if: tag IS present
    before_install:
      - sudo apt-get update
      - sudo apt-get install -y qemu-system-aarch64
    os: linux
    services: docker
    script:
    - VM_ARCH=aarch64 ./build/release-build-appimage.bash
  - name: windows build
    if: tag IS present
    os: linux
    services: docker
    script:
    - |
      docker run --rm \
        $(env | \
          grep -Eo '^[^\s=]*(DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_)[^\s=]*' | \
          sed '/^$/d;s/^/-e /' | \
          paste -sd ' ' \
        ) \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "./build/release-build-electron.bash --win"
  - name: osx build
    if: tag IS present
    script:
    - ./build/release-build-electron.bash --mac

