jobs:
  include:
    - name: "windows - node 8"
      os: windows
      language: node_js
      node_js: "8"
      install:
      before_script:
        - npm run bootstrap
    - name: "windows - node 10"
      os: windows
      language: node_js
      node_js: "10"
      install:
      before_script:
        - npm install lerna
        - npm run bootstrap
    - name: "linux - node 8"
      os: linux
      language: node_js
      node_js: "8"
      install:
      before_script:
        - npm install lerna
        - npm run bootstrap
    - name: "linux - node 10"
      os: linux
      language: node_js
      node_js: "10"
      install:
      before_script:
        - npm install lerna
        - npm run bootstrap
    - name: "osx - node 8"
      os: osx
      language: node_js
      node_js: "8"
      install:
      before_script:
        - npm install lerna
        - npm run bootstrap
    - name: "osx - node 10"
      os: osx
      language: node_js
      node_js: "10"
      install:
      before_script:
        - npm install lerna
        - npm run bootstrap